apiVersion: v1
kind: Service
metadata:
  labels:
    app: greenlight
  name: greenlight
  namespace: greenlight-ns
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: greenlight
  type: ClusterIP
